// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Data;

namespace Shop.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20221108133553_Inital_Data")]
    partial class Inital_Data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AutoPartsStoreProduct", b =>
                {
                    b.Property<int>("AutoPartsStoresId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("AutoPartsStoresId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("AutoPartsStoreProduct");

                    b.HasData(
                        new
                        {
                            AutoPartsStoresId = 2,
                            ProductsId = 1
                        },
                        new
                        {
                            AutoPartsStoresId = 1,
                            ProductsId = 1
                        },
                        new
                        {
                            AutoPartsStoresId = 3,
                            ProductsId = 2
                        },
                        new
                        {
                            AutoPartsStoresId = 1,
                            ProductsId = 3
                        },
                        new
                        {
                            AutoPartsStoresId = 2,
                            ProductsId = 3
                        });
                });

            modelBuilder.Entity("Shop.Data.Models.AutoPartsStore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AutoPartsStore");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Minsk store"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Brest store"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gomel store"
                        });
                });

            modelBuilder.Entity("Shop.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Stopping support",
                            Price = 108.95
                        },
                        new
                        {
                            Id = 2,
                            Description = "Clutch kit",
                            Price = 98.170000000000002
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bulb",
                            Price = 85.049999999999997
                        });
                });

            modelBuilder.Entity("AutoPartsStoreProduct", b =>
                {
                    b.HasOne("Shop.Data.Models.AutoPartsStore", null)
                        .WithMany()
                        .HasForeignKey("AutoPartsStoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Data.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
